package org.app.musannif;

import org.junit.platform.suite.api.SelectPackages;
import org.junit.platform.suite.api.Suite;
import org.junit.platform.suite.api.SuiteDisplayName;

/**
 * Master test suite for the Musannif project.
 *
 * HOW TO RUN WITH COVERAGE IN INTELLIJ IDEA:
 * ──────────────────────────────────────────
 * 1. Right-click this file in the Project panel → "Run 'AllTests' with Coverage"
 *    (or click the green ▶ gutter icon → "Run with Coverage")
 *
 * 2. The Coverage tool window opens automatically showing per-class, per-package,
 *    and per-line percentages for every class under org.app.musannif.
 *
 * 3. To view the HTML report generated by JaCoCo via Maven:
 *      mvn clean test
 *    then open:  target/site/jacoco/index.html
 *
 * COVERED TEST CLASSES:
 * ─────────────────────
 *   model:
 *     - FileOrganizerFacadeTest
 *     - FileOrganizerTest
 *     - FileScannerTest
 *     - HelperMethodsTest
 *     - OrganizationMementoTest
 *     - ScannedFileTest
 *
 *   model.category:
 *     - CategoriesTest
 *     - DateFileCategorizerTest
 *     - DateFilterDecoratorTest
 *     - ExtensionFileCategorizerTest
 *     - FileHandlerChainTest
 *     - SingleExtensionCategoryTest
 *     - SizeFilterDecoratorTest
 *
 *   model.command:
 *     - CommandHistoryTest
 *     - FileCommandsTest
 *
 *   model.history:
 *     - OperationHistoryTest  (includes OperationRecordTest nested class)
 *
 * DEPENDENCIES REQUIRED (already in pom.xml):
 * ────────────────────────────────────────────
 *   junit-jupiter-api       5.x
 *   junit-jupiter-engine    5.x
 *   junit-platform-suite    5.x   ← add this if missing (see pom.xml snippet below)
 *   junit-platform-launcher 1.x   ← add this if missing
 *
 * pom.xml additions needed:
 * ─────────────────────────
 *   <dependency>
 *       <groupId>org.junit.platform</groupId>
 *       <artifactId>junit-platform-suite</artifactId>
 *       <version>1.12.1</version>
 *       <scope>test</scope>
 *   </dependency>
 *   <dependency>
 *       <groupId>org.junit.platform</groupId>
 *       <artifactId>junit-platform-launcher</artifactId>
 *       <version>1.12.1</version>
 *       <scope>test</scope>
 *   </dependency>
 */
@Suite
@SuiteDisplayName("Musannif — All Tests")
@SelectPackages("org.app.musannif")
public class AllTests {
    // This class is intentionally empty.
    // The @Suite + @SelectPackages annotations instruct JUnit Platform to
    // discover and run every test class found under org.app.musannif
    // (including all sub-packages: model, model.category, model.command,
    //  model.history, etc.).
}
